# Generated by Django 4.1.5 on 2023-01-29 14:02

import Payments.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0002_school_school_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_grade', models.CharField(max_length=50, null=True)),
                ('academic_session', models.CharField(max_length=50)),
                ('academic_term', models.CharField(max_length=50)),
                ('amount_paid', models.BigIntegerField(blank=True, null=True)),
                ('amount_to_be_paid', models.BigIntegerField(blank=True, null=True)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('amount_in_debt', models.BigIntegerField(blank=True, null=True)),
                ('has_been_processed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('payment_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=9, max_length=9, prefix='', unique=True)),
                ('image', models.ImageField(null=True, upload_to='reciepts')),
                ('hash', models.CharField(blank=True, max_length=100, null=True)),
                ('ref', models.CharField(max_length=100)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dashboard.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=models.SET(Payments.models.payment.get_deleted_user_instance), to='Dashboard.student')),
            ],
        ),
    ]
