# Generated by Django 4.1.5 on 2023-01-16 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(max_length=70, null=True, upload_to='Profiles')),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('security_key', models.CharField(max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
