# Generated by Django 4.1.5 on 2023-01-16 00:16

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('first_term_school_fee', models.BigIntegerField(blank=True, default=0)),
                ('first_term_hostel_fee', models.BigIntegerField(blank=True, default=0)),
                ('first_term_bus_fee', models.BigIntegerField(blank=True, default=0)),
                ('second_term_school_fee', models.BigIntegerField(blank=True, default=0)),
                ('second_term_hostel_fee', models.BigIntegerField(blank=True, default=0)),
                ('second_term_bus_fee', models.BigIntegerField(blank=True, default=0)),
                ('third_term_school_fee', models.BigIntegerField(blank=True, default=0)),
                ('third_term_hostel_fee', models.BigIntegerField(blank=True, default=0)),
                ('third_term_bus_fee', models.BigIntegerField(blank=True, default=0)),
                ('grade_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=9, max_length=9, prefix='', unique=True)),
                ('next_class_to_be_promoted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.grade')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school_address', models.TextField()),
                ('logo', models.ImageField(blank=True, max_length=70, upload_to='Profiles')),
                ('school_background', models.ImageField(blank=True, upload_to='School Background')),
                ('email', models.EmailField(max_length=254)),
                ('budget', models.BigIntegerField(null=True)),
                ('mobile_number', models.CharField(max_length=50)),
                ('brand_color', models.CharField(max_length=50)),
                ('accent_color', models.CharField(max_length=50)),
                ('academic_session', models.CharField(choices=[('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022'), ('2022/2023', '2022/2023'), ('2023/2024', '2023/2024'), ('2024/2025', '2024/2025')], max_length=50)),
                ('current_term', models.CharField(choices=[('FIRST TERM', 'FIRST TERM'), ('SECOND TERM', 'SECOND TERM'), ('THIRD TERM', 'THIRD TERM')], max_length=50)),
                ('account_number', models.BigIntegerField()),
                ('school_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=9, max_length=9, prefix='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=200, unique=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name="parent's email")),
                ('parent_phone_number', models.CharField(blank=True, max_length=50)),
                ('is_following_bus', models.BooleanField(default=False)),
                ('is_in_hostel', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('OUTSTANDING', 'OUTSTANDING'), ('IN DEBT', 'IN DEBT')], default='IN DEBT', max_length=50)),
                ('amount_in_debt', models.BigIntegerField(default=0)),
                ('is_outstanding', models.BooleanField(default=False)),
                ('outstanding_amount', models.BigIntegerField(default=0)),
                ('grade', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.grade')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.school')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.school'),
        ),
    ]
