# Generated by Django 4.1.5 on 2023-01-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
